version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rd1wakar/mern-demo-frontend:${TAG}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rd1wakar/mern-demo-backend:${TAG}
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
